### ISSUE TITLE
App won't start

### ISSUE THREAD

**Issue by MrGung** [jcreager/shipping-cljs#5]
Hi,

I cloned your repo, started the REPL with `lein repl` calling `(start)` results in 

> Execution error at cprop.core/load-config (core.cljc:26).
> could not find a non empty configuration file to load. looked in the classpath (as a "resource") and on a file system via "conf" system property

I find several `config.edn`-files in the repo (e.g. in `env\dev\resources\`) but I don't have a clue how to activate any of these...

**Comment by endrebak** [comment]
You are missing some config files that are not included by default. Here is a fix:

https://llsouder.blogspot.com/2018/10/more-yak-shaving-in-clojure.html
